storefront/core/urls.py
from django.views.generic import TemplateView
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView

from . import views
from rest_framework.routers import DefaultRouter

app_name = 'core'

router = DefaultRouter()
router.register('SignUp', views.SignUpViewSet, basename='SignUp')



# URLConf
urlpatterns = [
    path('', TemplateView.as_view(template_name='core/index.html'), name='Home'),
    path('SignIn/', views.SignInView, name='SignIn'),
    # path('signUp/', views.SignUpViewSet, name='signUp'),
    #  path('profile/', views.UserProfileView.as_view(), name='user-profile'),
    # path('register/', views.CustomUserCreateView.as_view({'post': 'create'}), name='user-registration'),
    # path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
]


urlpatterns += router.urls

storefront/store/urls.py
from django.urls import path
from django.urls.conf import include
from rest_framework_nested import routers
from . import views

app_name = 'store'



router = routers.DefaultRouter()
router.register('products', views.ProductViewSet, basename='products')
router.register('collections', views.CollectionViewSet)
router.register('carts', views.CartViewSet)
router.register('customers', views.CustomerViewSet)
router.register('orders', views.OrderViewSet, basename='orders')

products_router = routers.NestedDefaultRouter(
    router, 'products', lookup='product')
products_router.register('reviews', views.ReviewViewSet,
                         basename='product-reviews')
products_router.register('images', views.ProductImageViewSet, basename='product-images')


carts_router = routers.NestedDefaultRouter(router, 'carts', lookup='cart')
carts_router.register('items', views.CartItemViewSet, basename='cart-items')

# urlpatterns =[
#     path('products_page', views.\)
# ]

# URLConf
urlpatterns = router.urls + products_router.urls + carts_router.urls

urlpatterns += [
    path('products/products_page/', views.ProductViewSet.as_view({'get': 'products_page'}), name='products_page'),
]

storefront/store/models.py
from django.contrib import admin
from django.conf import settings
from django.core.validators import MinValueValidator, FileExtensionValidator
from django.db import models
from .validators import *
from uuid import uuid4


class Promotion(models.Model):
    description = models.CharField(max_length=255)
    discount = models.FloatField()


class Collection(models.Model):
    title = models.CharField(max_length=255)
    featured_product = models.ForeignKey(
        'Product', on_delete=models.SET_NULL, null=True, related_name='+', blank=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['title']


class Product(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True)
    unit_price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[MinValueValidator(1)])
    inventory = models.IntegerField(validators=[MinValueValidator(0)])
    last_update = models.DateTimeField(auto_now=True)
    collection = models.ForeignKey(
        Collection, on_delete=models.PROTECT, related_name='products')
    promotions = models.ManyToManyField(Promotion, blank=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['title']

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete= models.CASCADE, related_name= 'images')
    image = models.ImageField(upload_to= 'store/images', validators= [validate_file_size])
    
    
    #You can also use FileField to use ANY file. So for your data project your can use this for CSV files ex:
    #file = models.FileField(upload_to = 'store/images', validators[FileExtensionValidator(allowed_extensions = ['csv'])])
                                                            #^validating to make sure the file type is a        ^csv file





class Customer(models.Model):
    MEMBERSHIP_BRONZE = 'B'
    MEMBERSHIP_SILVER = 'S'
    MEMBERSHIP_GOLD = 'G'

    MEMBERSHIP_CHOICES = [
        (MEMBERSHIP_BRONZE, 'Bronze'),
        (MEMBERSHIP_SILVER, 'Silver'),
        (MEMBERSHIP_GOLD, 'Gold'),
    ]
    phone = models.CharField(max_length=255)
    birth_date = models.DateField(null=True, blank=True)
    membership = models.CharField(
        max_length=1, choices=MEMBERSHIP_CHOICES, default=MEMBERSHIP_BRONZE)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    @admin.display(ordering='user__first_name')
    def first_name(self):
        return self.user.first_name

    @admin.display(ordering='user__last_name')
    def last_name(self):
        return self.user.last_name

    class Meta:
        ordering = ['user__first_name', 'user__last_name']
        permissions = [
            ('view_history', 'Can view history')
        ]


class Order(models.Model):
    PAYMENT_STATUS_PENDING = 'P'
    PAYMENT_STATUS_COMPLETE = 'C'
    PAYMENT_STATUS_FAILED = 'F'
    PAYMENT_STATUS_CHOICES = [
        (PAYMENT_STATUS_PENDING, 'Pending'),
        (PAYMENT_STATUS_COMPLETE, 'Complete'),
        (PAYMENT_STATUS_FAILED, 'Failed')
    ]

    placed_at = models.DateTimeField(auto_now_add=True)
    payment_status = models.CharField(
        max_length=1, choices=PAYMENT_STATUS_CHOICES, default=PAYMENT_STATUS_PENDING)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)

    class Meta:
        permissions = [
            ('cancel_order', 'Can cancel order')
        ]


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name='items')
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT, related_name='orderitems')
    quantity = models.PositiveSmallIntegerField()
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)


class Address(models.Model):
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE)


class Cart(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True)


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)]
    )

    class Meta:
        unique_together = [['cart', 'product']]


class Review(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField(auto_now_add=True)

storefront/store/views.py
from store.permissions import FullDjangoModelPermissions, IsAdminOrReadOnly, ViewCustomerHistoryPermission
from store.pagination import DefaultPagination
from django.db.models.aggregates import Count
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action, permission_classes
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.mixins import CreateModelMixin, DestroyModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.permissions import AllowAny, DjangoModelPermissions, DjangoModelPermissionsOrAnonReadOnly, IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework import generics
from rest_framework import status
from .filters import ProductFilter
from .models import *
from .serializers import *




class ProductViewSet(ModelViewSet, generics.RetrieveAPIView):
    queryset = Product.objects.prefetch_related('images').all()
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = ProductFilter
    pagination_class = DefaultPagination
    permission_classes = [IsAdminOrReadOnly]
    search_fields = ['title', 'description']
    ordering_fields = ['unit_price', 'last_update']
    renderer_classes=[TemplateHTMLRenderer]
                    #^used to render customer templates 
    def get_serializer_context(self):
        return {'request': self.request}

    def destroy(self, request, *args, **kwargs):
        if OrderItem.objects.filter(product_id=kwargs['pk']).count() > 0:
            return Response({'error': 'Product cannot be deleted because it is associated with an order item.'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

        return super().destroy(request, *args, **kwargs)
    
    @action(detail=False, methods=['get'])
    def products_page(self, request):
        # Get your data - for example, all products
        products = self.get_queryset()
        return Response({'products': products}, template_name='store/products_page.html')
    
    def retrieve(self, request, *args, **kwargs):
        product = self.get_object()
        return Response({'product': product}, template_name='store/product_detail.html')
    

class ProductImageViewSet(ModelViewSet):
    serializer_class = ProductImageSerializer
    
    def get_queryset(self):
        
        return ProductImage.objects.filter(product_id = self.kwargs['product_pk'])
    
    def get_serializer_context(self):
        return {'product_id': self.kwargs['product_pk']}



class CollectionViewSet(ModelViewSet):
    queryset = Collection.objects.annotate(
        products_count=Count('products')).all()
    serializer_class = CollectionSerializer
    permission_classes = [IsAdminOrReadOnly]

    def destroy(self, request, *args, **kwargs):
        if Product.objects.filter(collection_id=kwargs['pk']):
            return Response({'error': 'Collection cannot be deleted because it includes one or more products.'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

        return super().destroy(request, *args, **kwargs)


class ReviewViewSet(ModelViewSet):
    serializer_class = ReviewSerializer

    def get_queryset(self):
        return Review.objects.filter(product_id=self.kwargs['product_pk'])

    def get_serializer_context(self):
        return {'product_id': self.kwargs['product_pk']}


class CartViewSet(CreateModelMixin,
                  RetrieveModelMixin,
                  DestroyModelMixin,
                  GenericViewSet):
    queryset = Cart.objects.prefetch_related('items__product').all()
    serializer_class = CartSerializer
    
    def get_serializer_context(self):
        
        # This method returns a context dictionary to the serializer
        context = super().get_serializer_context()
        context.update({'request': self.request})
                #send request data over to extract image 
        return context
    
    
class CartItemViewSet(ModelViewSet):
    http_method_names = ['get', 'post', 'patch', 'delete']

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return AddCartItemSerializer
        elif self.request.method == 'PATCH':
            return UpdateCartItemSerializer
        return CartItemSerializer

    def get_serializer_context(self):
        return {'cart_id': self.kwargs['cart_pk']}

    def get_queryset(self):
        return CartItem.objects \
            .filter(cart_id=self.kwargs['cart_pk']) \
            .select_related('product')


class CustomerViewSet(ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    permission_classes = [IsAdminUser]

    @action(detail=True, permission_classes=[ViewCustomerHistoryPermission])
    def history(self, request, pk):
        return Response('ok')

    @action(detail=False, methods=['GET', 'PUT'], permission_classes=[IsAuthenticated])
    def me(self, request):
        customer = Customer.objects.get(
            user_id=request.user.id)
        if request.method == 'GET':
            serializer = CustomerSerializer(customer)
            return Response(serializer.data)
        elif request.method == 'PUT':
            serializer = CustomerSerializer(customer, data=request.data)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    http_method_names = ['get', 'post', 'patch', 'delete', 'head', 'options']

    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsAdminUser()]
        return [IsAuthenticated()]

    def create(self, request, *args, **kwargs):
        serializer = CreateOrderSerializer(
            data=request.data,
            context={'user_id': self.request.user.id})
        serializer.is_valid(raise_exception=True)
        order = serializer.save()
        serializer = OrderSerializer(order)
        return Response(serializer.data)

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return CreateOrderSerializer
        elif self.request.method == 'PATCH':
            return UpdateOrderSerializer
        return OrderSerializer

    def get_queryset(self):
        user = self.request.user

        if user.is_staff:
            return Order.objects.all()

        customer_id = Customer.objects.only(
            'id').get(user_id=user.id)
        return Order.objects.filter(customer_id=customer_id)

storefront/store/templates/store/header_with_cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title }} - MeowMart</title>
    <link href="{% static 'cart.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
</head>
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <header class="bg-white shadow relative" >
        <div class="container mx-auto px-6 py-3">
            <div class="flex items-center justify-between">
                <div class="flex items-center">
                    <a href="{% url 'core:Home' %}" class="text-gray-800 text-xl font-bold md:text-2xl hover:text-gray-700">
                        <img src="{% static 'core/logo.jpg' %}" alt="MeowMart Logo" class="h-10 w-10 md:h-16 md:w-16">
                    </a>
                    <nav class="md:ml-16">
                        <ul class="items-center justify-center space-x-8 md:flex">
                            <li><a href="{% url 'core:Home' %}" class="text-gray-800 hover:text-purple-600">Home</a></li>
                            <li><a href="{% url 'store:products_page' %}" class="text-gray-800 hover:text-purple-600">Products</a></li>
                            <li><a href="{% url 'core:SignIn' %}" class="text-gray-800 hover:text-purple-600">Sign In</a></li>
                            <li><a href="{% url 'core:SignUp-SignUpForm' %}" class="text-gray-800 hover:text-purple-600">Create Account</a></li>
                        </ul>
                    </nav>
                </div>

                    <div class="cart-summary relative cursor-pointer" onclick="toggleCart()">
                        <img src="{% static 'cat_cart.jpg' %}" alt="Cart" class="cart-icon h-12 w-12">
                        <span id="cart-count" class="cart-quantity">0</span>
                      </div>
                      <div id="cart-dropdown" class="cart-dropdown hidden absolute right-0 mt-2 w-48 bg-white shadow-md z-50">
                        <!-- Cart items will be dynamically inserted here -->
                        <ul id="cart-items-list">
                          <!-- Dynamically filled by JavaScript -->
                        </ul>

                      </div>               
                </div>
            </div>
        </div>
    </header>

storefront/store/templates/store/product_detail.html
{% load static %}
{%include 'store/header_with_cart.html'%}

    <main class="flex flex-col items-center px-4 sm:px-8 my-8">
        <div class="flex flex-col sm:flex-row justify-between items-start bg-white p-4 sm:p-6 rounded-lg shadow-lg w-full max-w-4xl">
            <div class="w-full sm:w-1/2 p-4">
                <img id="primary-image" src="{{ product.images.first.image.url }}" alt="{{ product.title }}" class="w-full h-auto object-cover rounded">
                <div class="flex justify-center mt-4">
                    <!-- Thumbnails -->
                    {% for image in product.images.all %}
                        <img onclick="updatePrimaryImage(this)" src="{{ image.image.url }}" alt="Thumbnail for {{ product.title }}" class="w-16 h-16 object-cover rounded-full m-1 cursor-pointer hover:opacity-75">
                    {% endfor %}
                </div>
            </div>
            <div class="w-full sm:w-1/2 p-4">
                <div>
                    <small class="uppercase text-gray-600 text-xs">{{ product.brand }}</small>
                    <h1 class="text-2xl font-bold my-2">{{ product.title }}</h1>
                    <span class="text-xl text-gray-900">{{ product.unit_price }}</span>
                </div>
                <div class="mt-4">
                    <div class="flex items-center mb-4">
                        <button type="button" onclick="changeQuantity(-1)" class="text-lg rounded-l bg-gray-200 px-4 py-2 hover:bg-gray-300">-</button>
                        <input type="text" value="1" id="quantity-input" class="text-center bg-white px-4 py-2 w-16">
                        <button type="button" onclick="changeQuantity(1)" class="text-lg rounded-r bg-gray-200 px-4 py-2 hover:bg-gray-300">+</button>
                    </div>
                    <button class="w-full bg-purple-700 text-white px-4 py-2 rounded hover:bg-purple-800" type="button" onclick="addToCart('{{ product.id }}', document.getElementById('quantity-input').value)">Add to Cart</button>
                </div>
                <div class="product-description mt-4">
                    <p class="text-gray-700">{{ product.description }}</p>
                </div>
            </div>
        </div>
    </main>
    


    <script src="{% static 'CartFunctions.js' %}"></script>
    <script src="{% static 'CartVisual.js' %}"></script>

</body>
</html>

storefront/store/templates/store/product_detail_with_custom_css.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title }} - MeowMart</title>
    <link href="{% static 'product_detail.css' %}" rel="stylesheet">
    <link href="{% static 'cart.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <div class="header-content">
            <img src="{% static 'logo.jpg' %}" alt="MeowMart Logo" class="logo">
            <nav>
                <ul>
                    <li><a href="{% url 'core:Home' %}">Home</a></li>
                    <li><a href="{% url 'store:products_page' %}">Products</a></li>
                    <li><a href="{% url 'core:SignIn' %}">Sign In</a></li>
                    <li><a href="{% url 'core:SignUp-SignUpForm' %}">Create Account</a></li>
                </ul>
            </nav>
            <div class="cart-summary" onclick="toggleCart()">
                <img src="{% static 'cat_cart.jpg' %}" alt="Cart" class="cart-icon">
                <span id="cart-count" class="cart-quantity">0</span> <!-- Items text removed since you want the number inside the circle -->
            </div>
            
        </div>
        <div id="cart-dropdown" class="cart-dropdown">
            <ul id="cart-items-list">
                <!-- Cart items will be dynamically inserted here -->
            </ul>
        </div>
    </header>

    <main class="product-detail-main">
        <div class="product-content">
            <div class="product-gallery">
                <img id="primary-image" src="{{ product.images.first.image.url }}" alt="{{ product.title }}" class="primary-image">
                <!-- Thumbnails -->
                <div class="thumbnails">
                    {% for image in product.images.all %}
                        <img onclick="updatePrimaryImage(this)" src="{{ image.image.url }}" alt="Thumbnail for {{ product.title }}" class="thumbnail-image">
                    {% endfor %}
                </div>
            </div>
            <div class="product-info">
                <div class="product-detail-header">
                    <small class="store-name">MeowMart</small>
                    <h1 class="product-title">{{ product.title }}</h1>
                    <span class="product-price">Price: ${{ product.unit_price }}</span>
                </div>
                <div class="product-purchase-info">
                    <div class="quantity-selector">
                        <button type="button" onclick="changeQuantity(-1)">-</button>
                        <input type="text" value="1" id="quantity-input">
                        <button type="button" onclick="changeQuantity(1)">+</button>
                    </div>
                    <button class="add-to-cart-btn" type="button" onclick="addToCart('{{ product.id }}', document.getElementById('quantity-input').value)">Add to Cart</button>
                </div>
                <div class="product-detail-description">
                    <p>{{ product.description }}</p>
                </div>
            </div>
        </div>
    </main>


    <script src="{% static 'CartFunctions.js' %}"></script>
    <script src="{% static 'CartVisual.js' %}"></script>
    <script>


        document.addEventListener('DOMContentLoaded', function() {
            updateCartUI(); // This function should be defined in 'CartFunctions.js'
        });
    </script>
</body>
</html>

storefront/store/templates/store/products_page.html
{% load static %}
{%include 'store/header_with_cart.html'%}


<link rel="stylesheet" href="{% static 'product_page.css' %}">
    </header>
    <h1>All Products</h1>
    <div class="product-grid">
        {% for product in products %}
    <div class="product-item">
        <a href="{% url 'store:products-detail' pk=product.id %}">
            {% with product.images.all|first as first_image %}
                {% if first_image %}
                    <img src="{{ first_image.image.url }}" alt="{{ product.title }}">
                {% endif %}
            {% endwith %}
            <h3>{{ product.title }}</h3>
            </a>
            <p class="price">From ${{ product.unit_price }} USD</p>
            <!-- Other product details and actions -->
        </div>
    {% empty %}
        <p>No products available.</p>
    {% endfor %}
    
    </div>



    <script src="{% static 'CartFunctions.js' %}"></script>
    <script src="{% static 'CartVisual.js' %}"></script>
</body>
</html>